server:
  port: 8010
  servlet:
    context-path: /sign-jwt
    session:
      timeout: 60000

jwt:
  token-validity-in-seconds: 3000

spring:
  session:
    timeout: 30
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: girmi:session
  data:
    redis:
      repositories:
        enabled: true
      host: localhost
      password: develop
      port: 6379

clients:
  data:
    jpa:
      user: http://localhost:8042/data-jpa/user


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


logging:
  config: classpath:config/logging.xml
