server:
  port: 8010
  servlet:
    context-path: /sign-jwt
    session:
      tracking-modes:
        - cookie

jwt:
  token-validity-in-seconds: 3000

spring:
  session:
    timeout: 60
    redis:
      namespace: girmi:session
  data:
    redis:
      host: localhost
      password: develop
      port: 6379

clients:
  data:
    jpa:
      user: http://localhost:8042/data-jpa/user

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


logging:
  config: classpath:config/logging.xml
