server:
  port: 8042
  servlet:
    context-path: /data-jpa

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/develop?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: develop
    password: ENC(O7Ip4KEWuUE9DEMsHbhtIg==)
  jpa:
    show-sql: true