server:
  port: 8030
  servlet:
    context-path: /service-common

cors:
  allow:
    origins: http://localhost:4000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

rest-server:
  apis:
    data:
      mybatis:
        greeting: http://localhost:8041/data-mybatis/greeting

logging:
  config: classpath:config/logging.xml
