server:
  port: 8041
  servlet:
    context-path: /data-mybatis


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/develop?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: develop
    password: ENC(O7Ip4KEWuUE9DEMsHbhtIg==)

mybatis:
  mapper-locations:
    - classpath:mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:config/logging.xml


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
